apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-agent-sample-linux-deployment
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      app: cloudwatch-agent-sample-linux-deployment
  template:
    metadata:
      labels:
        app: cloudwatch-agent-sample-linux-deployment
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: amazonlinux
          image: amazonlinux
      restartPolicy: Always
status: {}