{{- if .Values.dcgmExporter.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcgm-exporter.name" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4 }}
    k8s-app: {{ include "dcgm-exporter.name" . }}-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.dcgmExporter.service.type }}
  ports:
  - name: "metrics"
    port: {{ .Values.dcgmExporter.service.port }}
    targetPort: {{ .Values.dcgmExporter.service.port }}
    protocol: TCP
  selector:
    k8s-app: dcgm-exporter
  internalTrafficPolicy: Local
{{- end }}
