apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "amazon-cloudwatch-observability.name" . }}-manager-role
rules:
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "create", "patch" ]
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "get","list","patch","update","watch" ]
- apiGroups: [ "" ]
  resources: [ "serviceaccounts" ]
  verbs: [ "create","delete","get","list","patch","update","watch" ]
- apiGroups: [ "" ]
  resources: [ "services" ]
  verbs: [ "create","delete","get","list","patch","update","watch" ]
- apiGroups: [ "apps" ]
  resources: [ "daemonsets" ]
  verbs: [ "create","delete","get","list","patch","update","watch" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments" ]
  verbs: [ "create","delete","get","list","patch","update","watch" ]
- apiGroups: [ "apps" ]
  resources: [ "statefulsets" ]
  verbs: [ "create","delete","get","list","patch","update","watch" ]
- apiGroups: [ "apps" ]
  resources: [ "replicasets" ]
  verbs: [ "get","list","watch" ]
- apiGroups: [ "cloudwatch.aws.amazon.com" ]
  resources: [ "amazoncloudwatchagents" ]
  verbs: [ "get","list","patch","update","watch" ]
- apiGroups: [ "cloudwatch.aws.amazon.com" ]
  resources: [ "amazoncloudwatchagents/finalizers" ]
  verbs: [ "get","patch","update" ]
- apiGroups: [ "cloudwatch.aws.amazon.com" ]
  resources: [ "amazoncloudwatchagents/status" ]
  verbs: [ "get","patch","update" ]
- apiGroups: [ "cloudwatch.aws.amazon.com" ]
  resources: [ "instrumentations" ]
  verbs: [ "get","list","patch","update","watch" ]
- apiGroups: [ "coordination.k8s.io" ]
  resources: [ "leases" ]
  verbs: [ "create","get","list","update" ]
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses" ]
  verbs: [ "create","delete","get","list","patch","update","watch" ]
- apiGroups: [ "route.openshift.io" ]
  resources: [ "routes", "routes/custom-host" ]
  verbs: [ "create","delete","get","list","patch","update","watch" ]
