apiVersion: v2
name: amazon-cloudwatch-observability
version: 1.2.0
appVersion: 1.0.0
description: A Helm chart for Amazon CloudWatch Observability
type: application
home: https://aws.amazon.com/cloudwatch/
sources:
- https://github.com/aws/amazon-cloudwatch-agent-operator
maintainers:
- name: straussb
- name: lisaguo
- name: kausyas
