name: Python E2E EKS Testing
on:
  push:

concurrency:
  group: 'e2e-cw-agent-python-operator-test'
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read


jobs:
  python-e2e-eks-test:
    uses: ./.github/workflows/appsignals-python-e2e-test.yml
    secrets: inherit
    with:
      test-cluster-name: 'e2e-cw-agent-operator-python-test'