name: AWS Cloudwatch Agent Operator build testing
env:
  TERRAFORM_AWS_ASSUME_ROLE_DURATION: 14400 # 4 hours

on:
  push:
    branches:
      - integ-test*  # CHANGE TO MAIN
    paths-ignore:
      - '**/*.md'
      - 'NOTICE'
      - 'LICENSE'
#      - '.github/**'
#      - '!.github/workflows/main-build.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
#  BuildAndUpload:
#    uses: ./.github/workflows/build-and-upload.yml
#    secrets: inherit
#    permissions:
#      id-token: write
#      contents: read

  EKSIntegrationTest:
    name: 'EKSIntegrationTest'
    runs-on: ubuntu-latest
#    needs: [ BuildAndUpload ]
    strategy:
      fail-fast: false
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-east-1
#          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }} --Error: The requested DurationSeconds exceeds the MaxSessionDuration set for this role.

#      - name: Create kubeconfig directory
#        run: mkdir -p ${{ github.workspace }}/.kube
#
#      - name: Set KUBECONFIG environment variable
#        run: echo KUBECONFIG="${{ github.workspace }}/.kube/config" >> $GITHUB_ENV

      - name: Install eksctl
        run: |
          mkdir ${{ github.workspace }}/eksctl
          curl -sLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
          tar -xzf eksctl_Linux_amd64.tar.gz -C ${{ github.workspace }}/eksctl && rm eksctl_Linux_amd64.tar.gz
          echo "${{ github.workspace }}/eksctl" >> $GITHUB_PATH

      - name: Update kubconfig with cluster
        run: |
          mkdir -p ${{ github.workspace }}/.kube
          aws eks update-kubeconfig --name cloudwatchagent-operator --region us-east-1 --kubeconfig ${{ github.workspace }}/.kube/config
          echo KUBECONFIG="${{ github.workspace }}/.kube/config" >> $GITHUB_ENV

      - name: Verify Kubectl version
        run: kubectl config view
