# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: OperatorIntegrationTest.yml
env:
  TERRAFORM_AWS_ASSUME_ROLE: ${{ secrets.TERRAFORM_AWS_ASSUME_ROLE }}
  ECR_OPERATOR_STAGING_IMAGE: ${{ secrets.ECR_OPERATOR_STAGING_IMAGE }}

on:
  push:
    branches:
      - main*
      - addOperatorIntgTest
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  AmazonCloudWatchAgentOperatorIntegrationTest:
    name: AmazonCloudWatchAgentOperatorIntegrationTest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

#      - name: Login to ECR
#        if: steps.cached_binaries.outputs.cache-hit == false
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: Set up Docker Buildx
#        if: steps.cached_binaries.outputs.cache-hit == false
#        uses: docker/setup-buildx-action@v1
#
#      - name: Set up QEMU
#        if: steps.cached_binaries.outputs.cache-hit == false
#        uses: docker/setup-qemu-action@v1
#
#      - name: Build Cloudwatch Agent Operator Image and push to ECR
#        uses: docker/build-push-action@v4
#        if: steps.cached_binaries.outputs.cache-hit == false
#        with:
#          file: ./Dockerfile
#          context: .
#          push: true
#          tags: ${{ env.ECR_OPERATOR_STAGING_IMAGE }}
#          platforms: linux/amd64, linux/arm64

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform apply
        uses: nick-fields/retry@v2
        with:
          max_attempts: 1
          timeout_minutes: 60 # EKS takes about 20 minutes to spin up a cluster and service on the cluster
          retry_wait_seconds: 5
          command: |
            cd integration-tests/terraform/testbuild
            terraform init
            if terraform apply --auto-approve; then
                cd cmd
                ./pod_status_test.sh
                if [ $? -ne 0 ]; then
                  echo "Pod is not in running state"
                  echo "TestCase 1: Daemonset Pod Running Status: FAIL"
                  terraform destroy  -auto-approve && exit 1
                else
                  echo "Pod in running state"
                  echo "TestCase 1: Daemonset Pod Running Status: PASS"  
                fi
                go run ./test_default_and_ns_instrumentation_main.go
                if [ $? -ne 0 ]; then
                  terraform destroy  -auto-approve && exit 1
                fi
            else
                terraform destroy  -auto-approve && exit 1
            fi

      - name: Terraform destroy
        if: ${{ cancelled() || failure() }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 8
          retry_wait_seconds: 5
          command: |
            cd integration-tests/terraform/testbuild
            terraform destroy -var="beta=true" --auto-approve
